"use client";

import { useEffect, useState } from "react";
import { Loader2, PlugZap, Shield, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { useShellStore } from "@/lib/shell-store";

type CustomConfig = { enabled: boolean; baseUrl: string; endpointPath: string; method: "GET" | "POST"; itemsPath: string; idField: string; statusField: string; updatedAtField: string; labelField: string; authHeader: string; authScheme: "Bearer" | "Raw"; hasToken: boolean; lastSyncAt: string | null; lastSyncStatus: string | null; lastSyncError: string | null };
const EMPTY: CustomConfig = { enabled: false, baseUrl: "", endpointPath: "/api/live-status", method: "GET", itemsPath: "statuses", idField: "studentCode", statusField: "status", updatedAtField: "updatedAt", labelField: "label", authHeader: "Authorization", authScheme: "Bearer", hasToken: false, lastSyncAt: null, lastSyncStatus: null, lastSyncError: null };
async function postCustom(body: Record<string, unknown>) { const response = await fetch("/api/custom-sync", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body), cache: "no-store" }); const payload = await response.json().catch(() => ({ ok: false })); if (!response.ok || !payload?.ok) throw new Error(payload?.error || "فشل Custom App"); return payload.data as CustomConfig & { connected?: boolean; count?: number }; }

export function CustomAppPanel() {
  const [config, setConfig] = useState<CustomConfig>(EMPTY);
  const [token, setToken] = useState("");
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const liveSyncEnabled = useShellStore((state) => state.settings.liveSyncEnabled === true);
  const liveSyncPollMs = useShellStore((state) => state.settings.liveSyncPollMs ?? 3000);
  const updateSettings = useShellStore((state) => state.updateSettings);
  const load = async () => { const response = await fetch("/api/custom-sync", { cache: "no-store" }); const payload = await response.json().catch(() => ({ ok: false })); if (payload?.ok) setConfig({ ...EMPTY, ...payload.data }); };
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const save = async () => { setBusy(true); setStatus(null); try { const next = await postCustom({ action: "config.save", ...config, ...(token.trim() ? { token: token.trim() } : {}) }); setConfig((current) => ({ ...current, ...next })); setToken(""); setStatus("تم حفظ إعداد Custom App مشفراً. الإرسال اللحظي سيبقى اختيارياً."); } catch (error) { setStatus(error instanceof Error ? error.message : "تعذر الحفظ"); } finally { setBusy(false); } };
  const test = async () => { setBusy(true); setStatus("جاري اختبار Custom App..."); try { const result = await postCustom({ action: "test" }); setStatus(`تم الاتصال بنجاح — ${result.count ?? 0} حالة مستلمة.`); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "فشل الاختبار"); } finally { setBusy(false); } };
  const clear = async () => { setBusy(true); try { const next = await postCustom({ action: "config.clearToken" }); setConfig({ ...EMPTY, ...next }); setToken(""); setStatus("تم حذف Token Custom App وتعطيل الربط."); } catch (error) { setStatus(error instanceof Error ? error.message : "تعذر حذف Token"); } finally { setBusy(false); } };
  const update = (patch: Partial<CustomConfig>) => setConfig((current) => ({ ...current, ...patch }));
  return <section className="rounded-lg border border-violet-500/30 bg-violet-500/5 p-3 space-y-2" dir="rtl">
    <div className="flex items-center gap-2"><PlugZap className="h-4 w-4 text-violet-500" /><div><div className="text-xs font-bold">Custom App Hook</div><div className="text-[10px] text-muted-foreground">لربط أي تطبيق خارجي يعيد حالات الطلاب بصيغة JSON. لا يدخل هذا Token إلى نظام AI.</div></div></div>
    <div className="flex items-center justify-between text-[10px]"><span>الربط مفعّل</span><Switch checked={config.enabled} onCheckedChange={(enabled) => update({ enabled })} /></div>
    <div className="rounded border border-emerald-500/30 bg-emerald-500/5 p-2 space-y-1.5"><div className="flex items-center justify-between text-[10px]"><span className="font-bold">Live App inbound للمعلم</span><Switch checked={liveSyncEnabled} onCheckedChange={(enabled) => updateSettings({ liveSyncEnabled: enabled })} /></div><div className="text-[9px] leading-4 text-muted-foreground">يستقبل إجابات App عبر <code>/api/live-sync</code> ويعرض الفهم في الشريط. لا يفتح مسار دخول للطلاب ولا يكتب إلى Moodle.</div><label className="block text-[9px]">فاصل السحب بالمللي ثانية<input type="number" min="1000" max="30000" step="500" value={liveSyncPollMs} onChange={(event) => updateSettings({ liveSyncPollMs: Math.max(1000, Math.min(30000, Number(event.target.value) || 3000)) })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px]" /></label></div>
    <div className="grid grid-cols-2 gap-1"><label className="text-[9px]">Base URL<input value={config.baseUrl} onChange={(e) => update({ baseUrl: e.target.value })} placeholder="https://app.example.com" className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px]" /></label><label className="text-[9px]">Endpoint<input value={config.endpointPath} onChange={(e) => update({ endpointPath: e.target.value })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px] font-mono" /></label><label className="text-[9px]">طريقة الطلب<select value={config.method} onChange={(e) => update({ method: e.target.value as "GET" | "POST" })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px]"><option value="GET">GET</option><option value="POST">POST</option></select></label><label className="text-[9px]">مسار القائمة<input value={config.itemsPath} onChange={(e) => update({ itemsPath: e.target.value })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px] font-mono" /></label></div>
    <div className="grid grid-cols-2 gap-1"><label className="text-[9px]">حقل الطالب<input value={config.idField} onChange={(e) => update({ idField: e.target.value })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px] font-mono" /></label><label className="text-[9px]">حقل الحالة<input value={config.statusField} onChange={(e) => update({ statusField: e.target.value })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px] font-mono" /></label><label className="text-[9px]">حقل التحديث<input value={config.updatedAtField} onChange={(e) => update({ updatedAtField: e.target.value })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px] font-mono" /></label><label className="text-[9px]">حقل الوصف<input value={config.labelField} onChange={(e) => update({ labelField: e.target.value })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px] font-mono" /></label></div>
    <div className="grid grid-cols-2 gap-1"><label className="text-[9px]">Header<input value={config.authHeader} onChange={(e) => update({ authHeader: e.target.value })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px]" /></label><label className="text-[9px]">نوع المصادقة<select value={config.authScheme} onChange={(e) => update({ authScheme: e.target.value as "Bearer" | "Raw" })} className="mt-1 h-7 w-full rounded border bg-background px-1.5 text-[10px]"><option value="Bearer">Bearer</option><option value="Raw">Raw</option></select></label></div>
    <label className="block text-[9px]">Token {config.hasToken && <span className="text-emerald-600">(محفوظ)</span>}<input type="password" value={token} onChange={(e) => setToken(e.target.value)} placeholder={config.hasToken ? "اتركه فارغاً للإبقاء عليه" : "Token التطبيق الخارجي"} className="mt-1 h-8 w-full rounded border bg-background px-2 text-[10px] font-mono" /></label>
    <div className="flex flex-wrap gap-1"><Button size="sm" className="h-8 text-[10px]" onClick={() => void save()} disabled={busy || !config.baseUrl}><Shield className="ml-1 h-3 w-3" /> حفظ مشفر</Button><Button size="sm" variant="outline" className="h-8 text-[10px]" onClick={() => void test()} disabled={busy || !config.hasToken}><PlugZap className="ml-1 h-3 w-3" /> اختبار</Button>{config.hasToken && <Button size="sm" variant="outline" className="h-8 text-[10px] text-red-600" onClick={() => void clear()} disabled={busy}><Trash2 className="ml-1 h-3 w-3" /> حذف Token</Button>}</div>
    {busy && <div className="flex items-center gap-1 text-[9px] text-muted-foreground"><Loader2 className="h-3 w-3 animate-spin" /> جارٍ التنفيذ...</div>}{status && <div className="rounded bg-secondary/40 p-2 text-[10px]">{status}</div>}{config.lastSyncAt && <div className="text-[9px] text-muted-foreground">آخر سحب: {new Date(config.lastSyncAt).toLocaleString("ar-EG")} — {config.lastSyncStatus === "ok" ? "ناجح" : config.lastSyncError || "غير مكتمل"}</div>}
  </section>;
}
