import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Loader2, MessageCircle, RefreshCw, Send, ShieldCheck, Webhook } from "lucide-react";
import { useShellStore } from "@/lib/shell-store";
import { localDb } from "@/lib/local-db";

type TelegramConfig = { enabled: boolean; autoSend: boolean; schedule: "session" | "weekly" | "monthly" | "manual"; hasToken: boolean; webhookUrl: string; lastSendAt: string | null; lastSendStatus: string | null; lastSendError: string | null };
type TelegramStudent = { id: string; name: string; studentCode: string; linked: boolean; parentTelegramUsername: string | null };

async function telegramPost<T>(body: Record<string, unknown>): Promise<T> { const response = await fetch("/api/telegram", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({ ok: false, error: "استجابة Telegram غير صالحة" })); if (!response.ok || !payload?.ok) throw new Error(payload?.error || "فشل طلب Telegram"); return payload.data as T; }

export function TelegramPanel() {
  const activeClassId = useShellStore((s) => s.activeClassId);
  const currentSessionId = useShellStore((s) => s.currentSessionId);
  const [config, setConfig] = useState<TelegramConfig | null>(null);
  const [token, setToken] = useState("");
  const [webhookUrl, setWebhookUrl] = useState("");
  const [webhookSecret, setWebhookSecret] = useState("");
  const [students, setStudents] = useState<TelegramStudent[]>([]);
  const [busy, setBusy] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const [scheduleId, setScheduleId] = useState<string | null>(null);
  const [queueCount, setQueueCount] = useState(0);

  const load = useCallback(async () => { try { const response = await fetch("/api/telegram", { cache: "no-store" }); const payload = await response.json(); if (!payload.ok) throw new Error(payload.error); setConfig(payload.data); setWebhookUrl(payload.data.webhookUrl || ""); const rows = await telegramPost<TelegramStudent[]>({ action: "students.codes", classId: activeClassId || undefined }); setStudents(rows); const schedules = await localDb.reports.listSchedules(activeClassId); const schedule = schedules.find((row) => row.kind === "telegram-report"); setScheduleId(typeof schedule?.id === "string" ? schedule.id : null); const queue = await localDb.telegramV10.listQueue("pending"); setQueueCount(queue.length); } catch (error) { setStatus(error instanceof Error ? error.message : "تعذر تحميل Telegram"); } }, [activeClassId]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  const nextRunAt = (frequency: TelegramConfig["schedule"]) => { const next = new Date(); if (frequency === "weekly") next.setDate(next.getDate() + 7); else if (frequency === "monthly") next.setMonth(next.getMonth() + 1); else next.setHours(next.getHours() + 1); return next.toISOString(); };
  const save = async () => { setBusy(true); try { const next = await telegramPost<TelegramConfig>({ action: "config.save", enabled: config?.enabled === true, autoSend: config?.autoSend === true, schedule: config?.schedule ?? "manual", token: token || undefined }); setConfig(next); setToken(""); if (next.enabled && next.autoSend && (next.schedule === "weekly" || next.schedule === "monthly")) { const saved = await localDb.reports.saveSchedule({ id: scheduleId ?? undefined, kind: "telegram-report", classId: activeClassId, frequency: next.schedule, enabled: true, nextRunAt: nextRunAt(next.schedule), timezone: "Africa/Cairo" }); setScheduleId(typeof saved.id === "string" ? saved.id : scheduleId); } else if (scheduleId) { await localDb.reports.completeSchedule({ id: scheduleId, enabled: false, nextRunAt: null }); } setStatus("تم حفظ إعداد Telegram والجدولة محلياً بشكل مشفر."); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "تعذر حفظ إعداد Telegram"); } finally { setBusy(false); } };
  const test = async () => { setBusy(true); try { const result = await telegramPost<{ connected: boolean; username?: string }>({ action: "test" }); setStatus(`الاتصال ناجح عبر @${result.username || "bot"}`); } catch (error) { setStatus(error instanceof Error ? error.message : "فشل اختبار Telegram"); } finally { setBusy(false); } };
  const setWebhook = async () => { setBusy(true); try { const result = await telegramPost<{ secretForSetup?: string }>({ action: "webhook.set", webhookUrl, secret: webhookSecret || undefined }); setWebhookSecret(""); setStatus(result.secretForSetup ? `تم إعداد Webhook. احفظ هذا السر مرة واحدة: ${result.secretForSetup}` : "تم إعداد Webhook بنجاح."); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "تعذر إعداد Webhook"); } finally { setBusy(false); } };
  const sendStudent = async (studentId: string) => { setBusy(true); try { await telegramPost({ action: "sendStudentReport", studentId, sessionId: currentSessionId || undefined }); setStatus("تم إرسال تقرير PDF وملخصه لولي الأمر."); } catch (error) { setStatus(error instanceof Error ? error.message : "تعذر إرسال التقرير"); } finally { setBusy(false); } };
  const sendAll = async () => { setBusy(true); try { const result = await telegramPost<{ total: number; sent: number; queued?: number }>({ action: "sendSessionReports", sessionId: currentSessionId || undefined }); setStatus(`تم إرسال ${result.sent} من ${result.total} تقريراً${result.queued ? `، وأضيف ${result.queued} إلى queue` : ""}.`); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "تعذر إرسال التقارير"); } finally { setBusy(false); } };
  const processQueue = async () => { setBusy(true); try { const result = await telegramPost<{ processed: number }>({ action: "queue.process", limit: 10 }); setStatus(`تمت معالجة ${result.processed} رسالة من queue.`); await load(); } catch (error) { setStatus(error instanceof Error ? error.message : "تعذر تشغيل queue"); } finally { setBusy(false); } };

  if (!config) return <div className="rounded-lg border p-3 text-xs text-muted-foreground">جاري تحميل إعدادات Telegram...</div>;
  return <section className="rounded-lg border border-sky-500/30 bg-sky-500/5 p-2.5 space-y-2" dir="rtl">
    <div className="flex items-center justify-between gap-2"><div className="flex items-center gap-1.5 text-xs font-bold"><MessageCircle className="w-3.5 h-3.5 text-sky-600" /> بوت تقارير أولياء الأمور</div><Switch checked={config.enabled} onCheckedChange={(value) => setConfig({ ...config, enabled: value })} /></div>
    <p className="text-[9px] text-muted-foreground">Token يبقى على الخادم مشفراً. الطالب لا يدخل المنصة؛ ولي الأمر يرسل كود الطالب إلى البوت بعد إعداد Webhook.</p>
    <input type="password" value={token} onChange={(event) => setToken(event.target.value)} placeholder={config.hasToken ? "Token محفوظ — اكتب قيمة جديدة فقط عند التغيير" : "123456:AA... Bot Token"} className="w-full h-8 rounded border border-border bg-background px-2 text-xs font-mono" />
    <div className="flex gap-1"><Button className="h-7 flex-1 text-[10px]" onClick={() => void save()} disabled={busy}><ShieldCheck className="w-3 h-3 ml-1" /> حفظ مشفر</Button><Button variant="outline" className="h-7 text-[10px]" onClick={() => void test()} disabled={busy || !config.hasToken}><RefreshCw className="w-3 h-3 ml-1" /> اختبار</Button></div>
    <div className="flex items-center justify-between text-[10px]"><span>إرسال تلقائي</span><Switch checked={config.autoSend} onCheckedChange={(value) => setConfig({ ...config, autoSend: value })} disabled={!config.enabled} /></div>
    <select value={config.schedule} onChange={(event) => setConfig({ ...config, schedule: event.target.value as TelegramConfig["schedule"] })} className="w-full h-8 rounded border border-border bg-background px-2 text-xs" disabled={!config.enabled}><option value="session">بعد إنهاء كل حصة</option><option value="weekly">أسبوعياً — جدولة فعلية</option><option value="monthly">شهرياً — جدولة فعلية</option><option value="manual">يدوي فقط</option></select>
    <div className="border-t border-border pt-2 space-y-1.5"><div className="flex items-center gap-1 text-[10px] font-bold"><Webhook className="w-3 h-3" /> إعداد Webhook</div><input value={webhookUrl} onChange={(event) => setWebhookUrl(event.target.value)} placeholder="https://your-domain.example/api/telegram" className="w-full h-8 rounded border border-border bg-background px-2 text-xs font-mono" /><input value={webhookSecret} onChange={(event) => setWebhookSecret(event.target.value)} placeholder="Secret اختياري — سيُولّد تلقائياً" className="w-full h-8 rounded border border-border bg-background px-2 text-xs font-mono" /><Button variant="outline" className="h-7 w-full text-[10px]" onClick={() => void setWebhook()} disabled={busy || !config.hasToken || !webhookUrl}>تسجيل Webhook آمن</Button></div>
    <div className="border-t border-border pt-2 space-y-1.5"><div className="flex items-center justify-between"><span className="text-[10px] font-bold">أكواد الطلاب والربط</span><Button size="sm" variant="outline" className="h-7 text-[10px]" onClick={() => void load()} disabled={busy}>تحديث</Button></div>{students.length === 0 ? <div className="text-[9px] text-muted-foreground">لا يوجد طلاب في الصف الحالي.</div> : students.map((student) => <div key={student.id} className="flex items-center gap-1 rounded border border-border bg-background/70 p-1.5"><div className="min-w-0 flex-1"><div className="text-[10px] font-bold truncate">{student.name}</div><div className="text-[9px] font-mono text-muted-foreground">{student.studentCode} · {student.linked ? `مربوط ${student.parentTelegramUsername ? `@${student.parentTelegramUsername}` : ""}` : "غير مربوط"}</div></div><Button size="sm" variant="outline" className="h-7 text-[9px] shrink-0" onClick={() => void sendStudent(student.id)} disabled={busy || !student.linked}><Send className="w-3 h-3 ml-1" /> إرسال</Button></div>)}</div>
    <Button className="h-8 w-full text-[10px]" onClick={() => void sendAll()} disabled={busy || !config.hasToken}><Send className="w-3 h-3 ml-1" /> إرسال تقارير كل أولياء الأمور المربوطين</Button>
    <div className="flex items-center gap-2 rounded border border-border bg-background/60 p-2 text-[9px]"><span className="flex-1">Queue المعلقة: <b>{queueCount}</b>{scheduleId ? " • الجدولة مفعّلة محلياً" : ""}</span><Button size="sm" variant="outline" className="h-7 text-[9px]" onClick={() => void processQueue()} disabled={busy || !config.hasToken || queueCount === 0}><RefreshCw className="w-3 h-3 ml-1" /> تشغيل retry</Button></div>
    {busy && <div className="flex items-center gap-1 text-[9px] text-muted-foreground"><Loader2 className="w-3 h-3 animate-spin" /> جاري التنفيذ...</div>}
    {status && <div className="rounded bg-background/70 p-1.5 text-[9px] text-muted-foreground whitespace-pre-wrap break-words">{status}</div>}
  </section>;
}
